title: Arash Sal Moslehian
email: arashsm79@yahoo.com
description: >-
    Prance with the mad and the livid
baseurl: ""
url: "https://arashsm79.github.io"
repository: arashsm79/arashsm79.github.io
github_username:  arashsm79

exclude:
  - flake.nix
  - flake.lock
  - gemset.nix
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
